name: 'TODO Asana Action'
description: 'Create Asana Task from TODOs'
inputs:
  asana-token:
    description: 'Asana Personal Access Token.'
    required: true
  project-ids:
    description: 'List of projects where task needs to be added'
    required: true
  workspace-id:
    description: 'Workspace id'
    required: true
branding:
  icon: 'list'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'