name: 'TODO Asana Action'
description: 'Create Asana Task from TODOs'
inputs:
  asana-token:
    description: 'Asana personal access token'
    required: true
  projects:
    description: 'List of project id(s) where task needs to be added'
    required: true
  workspace:
    description: 'Workspace id'
    required: true
  followers:
    description: 'User id(s) of followers to be added to the task'
    required: false
  user-mapping:
    description: 'Github to asana id of users'
    required: false
branding:
  icon: 'list'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'